refactor(yadm): Update bootstrap to make it more similar to original

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -16,13 +16,17 @@ if [[ ! -d "${BOOTSTRAP_D}" ]]; then
   exit 1
 fi
 
-find -L "${BOOTSTRAP_D}" \( -type f -or -type l \) -not -name '*##*' -not -name '*~$*' | sort -n |
-  while IFS= read -r bootstrap; do
-    if [[ -x "${bootstrap}" ]]; then
-      printf "${YELLOW}%s${NC}\n" "Executing ${bootstrap} ..."
-      if ! "${bootstrap}"; then
-        echo "Error: bootstrap '${bootstrap}' failed" >&2
-        exit 1
-      fi
+declare -a bootstraps
+while IFS= read -r bootstrap; do
+  bootstraps+=("$bootstrap")
+done < <(find -L "${BOOTSTRAP_D}" \( -type f -or -type l \) -not -name '*##*' -not -name '*~$*' | sort -n)
+
+for bootstrap in "${bootstraps[@]}"; do
+  if [[ -x "${bootstrap}" ]]; then
+    printf "${YELLOW}%s${NC}\n" "Executing ${bootstrap} ..."
+    if ! "${bootstrap}"; then
+      echo "Error: bootstrap '${bootstrap}' failed" >&2
+      exit 1
     fi
-  done
+  fi
+done
