yadm: Install vim plugins through bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -14,11 +14,13 @@ if [[ ! -d "${BOOTSTRAP_D}" ]]; then
   exit 1
 fi
 
-find -L "${BOOTSTRAP_D}" -type f | sort | while IFS= read -r bootstrap; do
-if [[ -x "${bootstrap}" && ! "${bootstrap}" =~ "##" && ! "${bootstrap}" =~ "~$" ]]; then
-  if ! "${bootstrap}"; then
-    echo "Error: bootstrap '${bootstrap}' failed" >&2
-    exit 1
-  fi
-fi
-done
+find -L "${BOOTSTRAP_D}" -type f | sort | \
+  while IFS= read -r bootstrap; do
+    if [[ -x "${bootstrap}" && ! "${bootstrap}" =~ "##" && ! "${bootstrap}" =~ "~$" ]]; then
+      echo "Executing ${bootstrap} ..."
+      if ! "${bootstrap}"; then
+        echo "Error: bootstrap '${bootstrap}' failed" >&2
+        exit 1
+      fi
+    fi
+  done
